// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package itcollege.team09.entities;

import org.springframework.beans.factory.annotation.Configurable;

privileged aspect AdminYksuseLiik_Roo_Configurable {
    
    declare @type: AdminYksuseLiik: @Configurable;
    
}
